kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: bgd-route
  namespace: bgd
  labels:
    app: bgd
    app.kubernetes.io/instance: bgd-app
spec:
  to:
    kind: Service
    name: bgd
  tls: null
  host: www.bgd.lab.net
  path: /
  port:
    targetPort: 8080

